// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.chargerlink.gateway.bean.device



object DeviceParkingProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChhiZWFuL0RldmljZVBhcmtpbmcucHJvdG8SE0NoYXJnZXJMaW5rLkdhdGV3YXkaFmJlYW4vRW51bVBhcmtpbmcucHJvdG8i+
  AIKEkRldmljZVBhcmtpbmdDTF92MhJECgxwYXJraW5nX3R5cGUYASACKA4yIS5DaGFyZ2VyTGluay5HYXRld2F5LlBrRGV2aWNlV
  HlwZVILcGFya2luZ1R5cGUSHQoKcGFya2luZ19pZBgCIAEoDVIJcGFya2luZ0lkEhsKCXZlbmRvcl9pZBgDIAEoCVIIdmVuZG9yS
  WQSIQoMbW9kZWxfbnVtYmVyGAQgASgJUgttb2RlbE51bWJlchIjCg1zZXJpYWxfbnVtYmVyGAUgASgJUgxzZXJpYWxOdW1iZXISK
  QoQZmlybXdhcmVfdmVyc2lvbhgGIAEoCVIPZmlybXdhcmVWZXJzaW9uEikKEHByb3RvY29sX3ZlcnNpb24YByABKAlSD3Byb3RvY
  29sVmVyc2lvbhIlCg5jbGllbnRfdmVyc2lvbhgIIAEoCVINY2xpZW50VmVyc2lvbhIbCglzaW1faWNjaWQYCSABKAlSCHNpbUljY
  2lkQnIKI2NvbS5jaGFyZ2VybGluay5nYXRld2F5LmJlYW4uZGV2aWNlUABaI2NvbS5jaGFyZ2VybGluay5nYXRld2F5LmJlYW4uZ
  GV2aWNlqgIjY29tLmNoYXJnZXJsaW5rLmdhdGV3YXkuYmVhbi5kZXZpY2U="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
      com.chargerlink.gateway.bean.common.EnumParkingProto.scalaDescriptor
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.chargerlink.gateway.bean.common.EnumParkingProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}