// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.chargerlink.gateway.bean.alarm



object AlarmVehicleProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChdiZWFuL0FsYXJtVmVoaWNsZS5wcm90bxITQ2hhcmdlckxpbmsuR2F0ZXdheRoZYmVhbi9BbGFybVBhcmFtZXRlci5wcm90b
  xoWYmVhbi9EYXRhVmVoaWNsZS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byKKAQoMQWxhcm1WZWhpY2xlEkMKDHZla
  GljbGVfZGF0YRgBIAIoCzIgLkNoYXJnZXJMaW5rLkdhdGV3YXkuRGF0YVZlaGljbGVSC3ZlaGljbGVEYXRhEjUKC2V4dGVuZF9kY
  XRhGGQgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueVIKZXh0ZW5kRGF0YSLMAQoOQWxhcm1WZWhpY2xlUmESRAoLYWxhcm1fcGFyY
  W0YASACKAsyIy5DaGFyZ2VyTGluay5HYXRld2F5LkFsYXJtUGFyYW1ldGVyUgphbGFybVBhcmFtEj0KCWRhdGFfbGlzdBgCIAMoC
  zIgLkNoYXJnZXJMaW5rLkdhdGV3YXkuRGF0YVZlaGljbGVSCGRhdGFMaXN0EjUKC2V4dGVuZF9kYXRhGGQgASgLMhQuZ29vZ2xlL
  nByb3RvYnVmLkFueVIKZXh0ZW5kRGF0YUJvCiJjb20uY2hhcmdlcmxpbmsuZ2F0ZXdheS5iZWFuLmFsYXJtUABaImNvbS5jaGFyZ
  2VybGluay5nYXRld2F5LmJlYW4uYWxhcm2qAiJjb20uY2hhcmdlcmxpbmsuZ2F0ZXdheS5iZWFuLmFsYXJt"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
      com.chargerlink.gateway.bean.alarm.AlarmParameterProto.scalaDescriptor,
      com.chargerlink.gateway.bean.data.DataVehicleProto.scalaDescriptor,
      com.google.protobuf.any.AnyProto.scalaDescriptor
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.chargerlink.gateway.bean.alarm.AlarmParameterProto.javaDescriptor,
      com.chargerlink.gateway.bean.data.DataVehicleProto.javaDescriptor,
      com.google.protobuf.any.AnyProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}