// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.chargerlink.gateway.bean.common



sealed trait PkDeviceStatus extends _root_.com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = PkDeviceStatus
  def isPkDeviceStatusUnlock: Boolean = false
  def isPkDeviceStatusUnlockHalf: Boolean = false
  def isPkDeviceStatusLock: Boolean = false
  def isPkDeviceStatusFree: Boolean = false
  def isPkDeviceStatusUsed: Boolean = false
  def isPkDeviceStatusOffline: Boolean = false
  def isPkDeviceStatusMaintain: Boolean = false
  def isPkDeviceStatusDisabled: Boolean = false
  def isPkDeviceStatusFailure: Boolean = false
  def isPkDeviceStatusPoweroff: Boolean = false
  def companion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[PkDeviceStatus] = com.chargerlink.gateway.bean.common.PkDeviceStatus
}

object PkDeviceStatus extends _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[PkDeviceStatus] {
  implicit def enumCompanion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[PkDeviceStatus] = this
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_UNLOCK extends PkDeviceStatus {
    val value = 0
    val index = 0
    val name = "PK_DEVICE_STATUS_UNLOCK"
    override def isPkDeviceStatusUnlock: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_UNLOCK_HALF extends PkDeviceStatus {
    val value = 1
    val index = 1
    val name = "PK_DEVICE_STATUS_UNLOCK_HALF"
    override def isPkDeviceStatusUnlockHalf: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_LOCK extends PkDeviceStatus {
    val value = 2
    val index = 2
    val name = "PK_DEVICE_STATUS_LOCK"
    override def isPkDeviceStatusLock: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_FREE extends PkDeviceStatus {
    val value = 10
    val index = 3
    val name = "PK_DEVICE_STATUS_FREE"
    override def isPkDeviceStatusFree: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_USED extends PkDeviceStatus {
    val value = 11
    val index = 4
    val name = "PK_DEVICE_STATUS_USED"
    override def isPkDeviceStatusUsed: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_OFFLINE extends PkDeviceStatus {
    val value = 100
    val index = 5
    val name = "PK_DEVICE_STATUS_OFFLINE"
    override def isPkDeviceStatusOffline: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_MAINTAIN extends PkDeviceStatus {
    val value = 101
    val index = 6
    val name = "PK_DEVICE_STATUS_MAINTAIN"
    override def isPkDeviceStatusMaintain: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_DISABLED extends PkDeviceStatus {
    val value = 102
    val index = 7
    val name = "PK_DEVICE_STATUS_DISABLED"
    override def isPkDeviceStatusDisabled: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_FAILURE extends PkDeviceStatus {
    val value = 110
    val index = 8
    val name = "PK_DEVICE_STATUS_FAILURE"
    override def isPkDeviceStatusFailure: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PK_DEVICE_STATUS_POWEROFF extends PkDeviceStatus {
    val value = 200
    val index = 9
    val name = "PK_DEVICE_STATUS_POWEROFF"
    override def isPkDeviceStatusPoweroff: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends PkDeviceStatus with _root_.com.trueaccord.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(PK_DEVICE_STATUS_UNLOCK, PK_DEVICE_STATUS_UNLOCK_HALF, PK_DEVICE_STATUS_LOCK, PK_DEVICE_STATUS_FREE, PK_DEVICE_STATUS_USED, PK_DEVICE_STATUS_OFFLINE, PK_DEVICE_STATUS_MAINTAIN, PK_DEVICE_STATUS_DISABLED, PK_DEVICE_STATUS_FAILURE, PK_DEVICE_STATUS_POWEROFF)
  def fromValue(value: Int): PkDeviceStatus = value match {
    case 0 => PK_DEVICE_STATUS_UNLOCK
    case 1 => PK_DEVICE_STATUS_UNLOCK_HALF
    case 2 => PK_DEVICE_STATUS_LOCK
    case 10 => PK_DEVICE_STATUS_FREE
    case 11 => PK_DEVICE_STATUS_USED
    case 100 => PK_DEVICE_STATUS_OFFLINE
    case 101 => PK_DEVICE_STATUS_MAINTAIN
    case 102 => PK_DEVICE_STATUS_DISABLED
    case 110 => PK_DEVICE_STATUS_FAILURE
    case 200 => PK_DEVICE_STATUS_POWEROFF
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = EnumParkingProto.javaDescriptor.getEnumTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = EnumParkingProto.scalaDescriptor.enums(1)
}